version: "3.9"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: postgres:latest
    container_name: hex-todo-db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONNECTION_STRING=postgres://your_user:your_password@db:5432/your_database?sslmode=disable
    depends_on:
      - db
volumes:
  postgres_data: